// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: client-streaming/proto/client-streaming.proto

package client_streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientStreamingServiceClient is the client API for ClientStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientStreamingServiceClient interface {
	Status(ctx context.Context, opts ...grpc.CallOption) (ClientStreamingService_StatusClient, error)
}

type clientStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStreamingServiceClient(cc grpc.ClientConnInterface) ClientStreamingServiceClient {
	return &clientStreamingServiceClient{cc}
}

func (c *clientStreamingServiceClient) Status(ctx context.Context, opts ...grpc.CallOption) (ClientStreamingService_StatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientStreamingService_ServiceDesc.Streams[0], "/client.streaming.ClientStreamingService/Status", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientStreamingServiceStatusClient{stream}
	return x, nil
}

type ClientStreamingService_StatusClient interface {
	Send(*StatusRequest) error
	CloseAndRecv() (*StatusResponse, error)
	grpc.ClientStream
}

type clientStreamingServiceStatusClient struct {
	grpc.ClientStream
}

func (x *clientStreamingServiceStatusClient) Send(m *StatusRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientStreamingServiceStatusClient) CloseAndRecv() (*StatusResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStreamingServiceServer is the server API for ClientStreamingService service.
// All implementations must embed UnimplementedClientStreamingServiceServer
// for forward compatibility
type ClientStreamingServiceServer interface {
	Status(ClientStreamingService_StatusServer) error
	mustEmbedUnimplementedClientStreamingServiceServer()
}

// UnimplementedClientStreamingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientStreamingServiceServer struct {
}

func (UnimplementedClientStreamingServiceServer) Status(ClientStreamingService_StatusServer) error {
	return status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedClientStreamingServiceServer) mustEmbedUnimplementedClientStreamingServiceServer() {
}

// UnsafeClientStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStreamingServiceServer will
// result in compilation errors.
type UnsafeClientStreamingServiceServer interface {
	mustEmbedUnimplementedClientStreamingServiceServer()
}

func RegisterClientStreamingServiceServer(s grpc.ServiceRegistrar, srv ClientStreamingServiceServer) {
	s.RegisterService(&ClientStreamingService_ServiceDesc, srv)
}

func _ClientStreamingService_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStreamingServiceServer).Status(&clientStreamingServiceStatusServer{stream})
}

type ClientStreamingService_StatusServer interface {
	SendAndClose(*StatusResponse) error
	Recv() (*StatusRequest, error)
	grpc.ServerStream
}

type clientStreamingServiceStatusServer struct {
	grpc.ServerStream
}

func (x *clientStreamingServiceStatusServer) SendAndClose(m *StatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientStreamingServiceStatusServer) Recv() (*StatusRequest, error) {
	m := new(StatusRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStreamingService_ServiceDesc is the grpc.ServiceDesc for ClientStreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.streaming.ClientStreamingService",
	HandlerType: (*ClientStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _ClientStreamingService_Status_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client-streaming/proto/client-streaming.proto",
}
