// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/code-gen/enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EyeColor int32

const (
	EyeColor_EYE_COLOR_UNKNOWN EyeColor = 0
	EyeColor_EYE_COLOR_BROWN   EyeColor = 1
	EyeColor_EYE_COLOR_BLUE    EyeColor = 2
	EyeColor_EYE_COLOR_GREEN   EyeColor = 3
)

// Enum value maps for EyeColor.
var (
	EyeColor_name = map[int32]string{
		0: "EYE_COLOR_UNKNOWN",
		1: "EYE_COLOR_BROWN",
		2: "EYE_COLOR_BLUE",
		3: "EYE_COLOR_GREEN",
	}
	EyeColor_value = map[string]int32{
		"EYE_COLOR_UNKNOWN": 0,
		"EYE_COLOR_BROWN":   1,
		"EYE_COLOR_BLUE":    2,
		"EYE_COLOR_GREEN":   3,
	}
)

func (x EyeColor) Enum() *EyeColor {
	p := new(EyeColor)
	*p = x
	return p
}

func (x EyeColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EyeColor) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_code_gen_enum_enum_proto_enumTypes[0].Descriptor()
}

func (EyeColor) Type() protoreflect.EnumType {
	return &file_proto_code_gen_enum_enum_proto_enumTypes[0]
}

func (x EyeColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EyeColor.Descriptor instead.
func (EyeColor) EnumDescriptor() ([]byte, []int) {
	return file_proto_code_gen_enum_enum_proto_rawDescGZIP(), []int{0}
}

type Enum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EyeColor       EyeColor `protobuf:"varint,1,opt,name=eye_color,json=eyeColor,proto3,enum=example.enum.EyeColor" json:"eye_color,omitempty"`
	EyeColorNumber EyeColor `protobuf:"varint,2,opt,name=eye_color_number,json=eyeColorNumber,proto3,enum=example.enum.EyeColor" json:"eye_color_number,omitempty"`
}

func (x *Enum) Reset() {
	*x = Enum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_code_gen_enum_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_gen_enum_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_proto_code_gen_enum_enum_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetEyeColor() EyeColor {
	if x != nil {
		return x.EyeColor
	}
	return EyeColor_EYE_COLOR_UNKNOWN
}

func (x *Enum) GetEyeColorNumber() EyeColor {
	if x != nil {
		return x.EyeColorNumber
	}
	return EyeColor_EYE_COLOR_UNKNOWN
}

var File_proto_code_gen_enum_enum_proto protoreflect.FileDescriptor

var file_proto_code_gen_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x7d,
	0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x33, 0x0a, 0x09, 0x65, 0x79, 0x65, 0x5f, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x52, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x10, 0x65,
	0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x0e, 0x65,
	0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2a, 0x5f, 0x0a,
	0x08, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x59, 0x45,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x52,
	0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c,
	0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x52, 0x45, 0x45, 0x4e, 0x10, 0x03, 0x42, 0x15,
	0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_code_gen_enum_enum_proto_rawDescOnce sync.Once
	file_proto_code_gen_enum_enum_proto_rawDescData = file_proto_code_gen_enum_enum_proto_rawDesc
)

func file_proto_code_gen_enum_enum_proto_rawDescGZIP() []byte {
	file_proto_code_gen_enum_enum_proto_rawDescOnce.Do(func() {
		file_proto_code_gen_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_code_gen_enum_enum_proto_rawDescData)
	})
	return file_proto_code_gen_enum_enum_proto_rawDescData
}

var file_proto_code_gen_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_code_gen_enum_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_code_gen_enum_enum_proto_goTypes = []interface{}{
	(EyeColor)(0), // 0: example.enum.EyeColor
	(*Enum)(nil),  // 1: example.enum.Enum
}
var file_proto_code_gen_enum_enum_proto_depIdxs = []int32{
	0, // 0: example.enum.Enum.eye_color:type_name -> example.enum.EyeColor
	0, // 1: example.enum.Enum.eye_color_number:type_name -> example.enum.EyeColor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_code_gen_enum_enum_proto_init() }
func file_proto_code_gen_enum_enum_proto_init() {
	if File_proto_code_gen_enum_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_code_gen_enum_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_code_gen_enum_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_code_gen_enum_enum_proto_goTypes,
		DependencyIndexes: file_proto_code_gen_enum_enum_proto_depIdxs,
		EnumInfos:         file_proto_code_gen_enum_enum_proto_enumTypes,
		MessageInfos:      file_proto_code_gen_enum_enum_proto_msgTypes,
	}.Build()
	File_proto_code_gen_enum_enum_proto = out.File
	file_proto_code_gen_enum_enum_proto_rawDesc = nil
	file_proto_code_gen_enum_enum_proto_goTypes = nil
	file_proto_code_gen_enum_enum_proto_depIdxs = nil
}
