// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/code-gen/test-dir/test.proto

package test_dir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ZipCode    string `protobuf:"bytes,2,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	CountyName string `protobuf:"bytes,3,opt,name=county_name,json=countyName,proto3" json:"county_name,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_proto_code_gen_test_dir_test_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *City) GetCountyName() string {
	if x != nil {
		return x.CountyName
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City     *City                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street   *City_Street          `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Building *City_Street_Building `protobuf:"bytes,3,opt,name=building,proto3" json:"building,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_code_gen_test_dir_test_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *Address) GetStreet() *City_Street {
	if x != nil {
		return x.Street
	}
	return nil
}

func (x *Address) GetBuilding() *City_Street_Building {
	if x != nil {
		return x.Building
	}
	return nil
}

type City_Street struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City *City  `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *City_Street) Reset() {
	*x = City_Street{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City_Street) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City_Street) ProtoMessage() {}

func (x *City_Street) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City_Street.ProtoReflect.Descriptor instead.
func (*City_Street) Descriptor() ([]byte, []int) {
	return file_proto_code_gen_test_dir_test_proto_rawDescGZIP(), []int{0, 0}
}

func (x *City_Street) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City_Street) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

type City_Street_Building struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number uint32       `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Street *City_Street `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
}

func (x *City_Street_Building) Reset() {
	*x = City_Street_Building{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City_Street_Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City_Street_Building) ProtoMessage() {}

func (x *City_Street_Building) ProtoReflect() protoreflect.Message {
	mi := &file_proto_code_gen_test_dir_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City_Street_Building.ProtoReflect.Descriptor instead.
func (*City_Street_Building) Descriptor() ([]byte, []int) {
	return file_proto_code_gen_test_dir_test_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *City_Street_Building) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City_Street_Building) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *City_Street_Building) GetStreet() *City_Street {
	if x != nil {
		return x.Street
	}
	return nil
}

var File_proto_code_gen_test_dir_test_proto protoreflect.FileDescriptor

var file_proto_code_gen_test_dir_test_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x69, 0x72, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x88, 0x02, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0xaf, 0x01, 0x0a, 0x06,
	0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x1a, 0x69, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x65, 0x74, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x22, 0xa4, 0x01,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x12, 0x3e, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x64, 0x65, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x69, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_code_gen_test_dir_test_proto_rawDescOnce sync.Once
	file_proto_code_gen_test_dir_test_proto_rawDescData = file_proto_code_gen_test_dir_test_proto_rawDesc
)

func file_proto_code_gen_test_dir_test_proto_rawDescGZIP() []byte {
	file_proto_code_gen_test_dir_test_proto_rawDescOnce.Do(func() {
		file_proto_code_gen_test_dir_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_code_gen_test_dir_test_proto_rawDescData)
	})
	return file_proto_code_gen_test_dir_test_proto_rawDescData
}

var file_proto_code_gen_test_dir_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_code_gen_test_dir_test_proto_goTypes = []interface{}{
	(*City)(nil),                 // 0: example.test.City
	(*Address)(nil),              // 1: example.test.Address
	(*City_Street)(nil),          // 2: example.test.City.Street
	(*City_Street_Building)(nil), // 3: example.test.City.Street.Building
}
var file_proto_code_gen_test_dir_test_proto_depIdxs = []int32{
	0, // 0: example.test.Address.city:type_name -> example.test.City
	2, // 1: example.test.Address.street:type_name -> example.test.City.Street
	3, // 2: example.test.Address.building:type_name -> example.test.City.Street.Building
	0, // 3: example.test.City.Street.city:type_name -> example.test.City
	2, // 4: example.test.City.Street.Building.street:type_name -> example.test.City.Street
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_code_gen_test_dir_test_proto_init() }
func file_proto_code_gen_test_dir_test_proto_init() {
	if File_proto_code_gen_test_dir_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_code_gen_test_dir_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_code_gen_test_dir_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_code_gen_test_dir_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City_Street); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_code_gen_test_dir_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City_Street_Building); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_code_gen_test_dir_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_code_gen_test_dir_test_proto_goTypes,
		DependencyIndexes: file_proto_code_gen_test_dir_test_proto_depIdxs,
		MessageInfos:      file_proto_code_gen_test_dir_test_proto_msgTypes,
	}.Build()
	File_proto_code_gen_test_dir_test_proto = out.File
	file_proto_code_gen_test_dir_test_proto_rawDesc = nil
	file_proto_code_gen_test_dir_test_proto_goTypes = nil
	file_proto_code_gen_test_dir_test_proto_depIdxs = nil
}
